In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import accuracy_score
import joblib


In [2]:
data = pd.read_excel(r"C:\Users\jaiva\OneDrive\Documents\python\project\fifa_wc_mens_match_dataset_1970_2022.xlsx")
data

,tournament_name,stage_name,group_name,group_stage,knockout_stage,replayed,replay,match_date,match_time,stadium_name,...,passes_attempted_h2,corners_h1,corners_h2,fouls_h1,fouls_h2,yellow_cards_h1,yellow_cards_h2,red_cards_h1,red_cards_h2,outcome
0,1970 FIFA Men's World Cup,group stage,Group 1,1,0,0,0,1970-05-31,12:00:00,Estadio Azteca,...,NaN,NaN,NaN,NaN,NaN,0,1,0,0,Draw
1,1970 FIFA Men's World Cup,group stage,Group 1,1,0,0,0,1970-05-31,12:00:00,Estadio Azteca,...,NaN,NaN,NaN,NaN,NaN,3,1,0,0,Draw
2,1970 FIFA Men's World Cup,group stage,Group 2,1,0,0,0,1970-06-03,16:00:00,La Bombonera,...,NaN,NaN,NaN,NaN,NaN,0,1,0,0,Loss
3,1970 FIFA Men's World Cup,group stage,Group 3,1,0,0,0,1970-06-03,16:00:00,Estadio Jalisco,...,NaN,NaN,NaN,NaN,NaN,1,0,0,0,Win
4,1970 FIFA Men's World Cup,group stage,Group 3,1,0,0,0,1970-06-06,16:00:00,Estadio Jalisco,...,NaN,NaN,NaN,NaN,NaN,0,1,0,0,Win
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1317,2022 FIFA Men's World Cup,semi-finals,not applicable,0,1,0,0,2022-12-14,22:00:00,Al Bayt Stadium,...,337.0,2.0,1.0,5.0,9.0,1,0,0,0,Loss
1318,2022 FIFA Men's World Cup,third-place match,not applicable,0,1,0,0,2022-12-17,18:00:00,Khalifa International Stadium,...,222.0,2.0,4.0,6.0,8.0,0,0,0,0,Win
1319,2022 FIFA Men's World Cup,third-place match,not applicable,0,1,0,0,2022-12-17,18:00:00,Khalifa International Stadium,...,295.0,2.0,1.0,5.0,10.0,0,2,0,0,Loss
1320,2022 FIFA Men's World Cup,final,not applicable,0,1,0,0,2022-12-18,18:00:00,Lusail Stadium,...,220.0,2.0,2.0,10.0,13.0,1,1,0,0,Win


In [3]:
print(data.shape)

(1322, 70)


In [4]:
print(data.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1322 entries, 0 to 1321
Data columns (total 70 columns):
 #   Column                         Non-Null Count  Dtype         
---  ------                         --------------  -----         
 0   tournament_name                1322 non-null   object        
 1   stage_name                     1322 non-null   object        
 2   group_name                     1322 non-null   object        
 3   group_stage                    1322 non-null   int64         
 4   knockout_stage                 1322 non-null   int64         
 5   replayed                       1322 non-null   int64         
 6   replay                         1322 non-null   int64         
 7   match_date                     1322 non-null   datetime64[ns]
 8   match_time                     1322 non-null   object        
 9   stadium_name                   1322 non-null   object        
 10  city_name                      1322 non-null   object        
 11  country_name     

In [5]:
print(data.isnull().sum())

tournament_name    0
stage_name         0
group_name         0
group_stage        0
knockout_stage     0
                  ..
yellow_cards_h1    0
yellow_cards_h2    0
red_cards_h1       0
red_cards_h2       0
outcome            0
Length: 70, dtype: int64


In [8]:
data = data.dropna().copy()

print(data.shape)

(768, 70)


In [24]:
label = LabelEncoder()

data['outcome'] = label.fit_transform(data['outcome'])

print(label.classes_)

[0 1 2]


In [51]:
X = data[['team_name', 'opponent_name', 'goals_for', 'goals_against', 'extra_time', 'penalty_shootout', 'penalties_for', 'penalties_against', 'result',
'possession', 'shots', 'shots_on_target', 'passes_completed', 'passes_attempted', 'corners', 'fouls', 'team_prior_win_rate','opp_prior_win_rate','team_curr_form_pts_avg','opp_curr_form_pts_avg','h2h_prior_win_rate']]

y = data['outcome']

In [20]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [56]:
rf = RandomForestClassifier(
    n_estimators=300,
    random_state=42)

rf.fit(x_train,y_train)

,n_estimators,300
,criterion,'gini'
,max_depth,None
,min_samples_split,2
,min_samples_leaf,1
,min_weight_fraction_leaf,0.0
,max_features,'sqrt'
,max_leaf_nodes,None
,min_impurity_decrease,0.0
,bootstrap,True
,oob_score,False


In [58]:
y_pred = rf.predict(x_test)

acc = accuracy_score(y_test, y_pred)

print("Accuracy =",acc)

Accuracy = 0.5194805194805194


In [42]:
joblib.dump(rf, "fifa2026_model.pkl")

['fifa2026_model.pkl']

In [48]:
print(data.columns.tolist())

['tournament_name', 'stage_name', 'group_name', 'group_stage', 'knockout_stage', 'replayed', 'replay', 'match_date', 'match_time', 'stadium_name', 'city_name', 'country_name', 'team_name', 'team_code', 'opponent_name', 'opponent_code', 'home_team', 'away_team', 'goals_for', 'goals_against', 'extra_time', 'penalty_shootout', 'penalties_for', 'penalties_against', 'result', 'is_host', 'yellow_cards', 'red_cards', 'possession', 'shots', 'shots_on_target', 'passes_completed', 'passes_attempted', 'corners', 'fouls', 'team_prior_matches', 'team_prior_win_rate', 'team_prior_goals_scored_avg', 'team_prior_goals_conceded_avg', 'opp_prior_matches', 'opp_prior_win_rate', 'opp_prior_goals_scored_avg', 'opp_prior_goals_conceded_avg', 'h2h_prior_matches', 'h2h_prior_win_rate', 'team_curr_form_pts_avg', 'team_curr_goals_scored_avg', 'team_curr_goals_conceded_avg', 'opp_curr_form_pts_avg', 'opp_curr_goals_scored_avg', 'opp_curr_goals_conceded_avg', 'possession_h1', 'possession_h2', 'shots_h1', 'shots_h

In [71]:
team_stats = data.groupby('team_name').agg({'team_prior_win_rate':'mean','team_curr_form_pts_avg':'mean'}).reset_index()

team_stats.head()

,team_name,team_prior_win_rate,team_curr_form_pts_avg
0,Algeria,0.269841,0.476190
1,Angola,0.000000,0.166667
2,Argentina,0.528874,1.897312
3,Australia,0.136041,0.607843
4,Belgium,0.350066,1.982456


In [62]:
team_stats.tail()

,team_name,team_prior_win_rate,team_curr_form_pts_avg
57,Turkey,0.333333,1.035714
58,Ukraine,0.000000,1.150000
59,United States,0.574879,1.112500
60,Uruguay,0.402561,1.368182
61,Wales,0.200000,0.500000


In [75]:
print(label.classes_)

[0 1 2]


In [76]:
from sklearn.metrics import confusion_matrix

print(confusion_matrix(y_test, y_pred))

[[ 3 16 14]
 [ 4 33 22]
 [ 3 15 44]]


In [81]:
print(team_stats.head())

   team_name  team_prior_win_rate  team_curr_form_pts_avg
0    Algeria             0.269841                0.476190
1     Angola             0.000000                0.166667
2  Argentina             0.528874                1.897312
3  Australia             0.136041                0.607843
4    Belgium             0.350066                1.982456


In [90]:
def predict_match(team1, team2):
    t1 = team_stats[team_stats['team_name'] == team1].iloc[0]
    t2 = team_stats[team_stats['team_name'] == team2].iloc[0]

    match = pd.DataFrame([[
        t1['team_prior_win_rate'],
        t2['team_prior_win_rate'],
        t1['team_curr_form_pts_avg'],
        t2['team_curr_form_pts_avg'],0.50]], 
        columns=['team_prior_win_rate', 'opp_prior_win_rate', 'team_curr_form_pts_avg', 'opp_curr_form_pts_avg', 'h2h_prior_win_rate'])

    pred = rf.predict(match)[0]
    result = label.inverse_transform([pred])[0]
    return result

In [95]:
print("Unique predictions:", np.unique(y_pred))

Unique predictions: [0 1 2]


In [ ]:
# 0 - Loss
# 1 - Draw
# 2 - Win
# Always shows the result of 1st team

In [98]:
print(predict_match("Turkey","Brazil"))

1
